server:
  port: 8080

spring:
  application:
    name: seed
  datasource:
    url: jdbc:mysql://192.168.31.186:3306/product-seed?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ****
    password: ********
    driver-class-name: com.mysql.cj.jdbc.Driver

info:
  api-doc: /swagger-ui.html

swagger:
  enable: true